### PR TITLE
ID#292 multifileupload as extension

### PR DESCRIPTION
**Pull request by der-dave**

### CODE REVIEW

**Comment by ChristianAchatz** [comment]
Hey dave,

thanks a lot for your contribution! Really appreaciated!

A couple of comments:

- With 2.0 I've removed external library component files (e.g. jQuery) along with http://tracker.adventure-php-framework.org/view.php?id=242 to avoid security issues with missing updates. I'd suggest to not deliver jQuery UI component files with the APF release and require users to include them as described in the demo files(s).
- How do you specify the upload directory? Is _data-url="uploaddirectory/php/"_ in _MultiFileUploadTag_ doing the trick?
- How does the upload process map to the existing _MultiFileDeleteAction_, _MultiFileGetFileAction_, and _MultiFileUploadAction_?
- What is the difference between _basic.html_ and _demo.html_? Seems singe vs. multiple file upload option? Maybe combine the demo into one file or even suggesting to integrate the file upload into the Sandbox combined with a little tutorial style intro.

Thoughts?

**Comment by ChristianAchatz** [comment]
Hey dave,

any news on above thoughts? Should we have a quick chat?

Best,
Christian

**Comment by ChristianAchatz** [comment]
Current discussion state summarized under http://forum.adventure-php-framework.org/viewtopic.php?f=5&t=5646&start=15#p20500.

**Comment by ChristianAchatz** [comment]
Hey dave,

let me know whether we can integrate the current state of branch "ID#292-multi-file-upload" into master code line.

Thanks!

Best,
Christian

**Comment by der-dave** [comment]
Hey Christian, as we discussed this topic already in the APF Forum we will close this request. I try to complete it later, but for now there is less time for that Topic.

Greets,
dave

**Pull request closed without merging**
