### PR TITLE
Add Coverage Report

### PR DESCRIPTION
**Pull request by martialblog**
Hello, 

I added some changes to improve the tests. Mainly that PHPUnit will now generate a coverage report. You should check out something like php-coveralls. 

Also:
- Added gitignore file (to ignore the vendor and report folder)
- Added composer.lock file, to ensure better reproducibility

### CODE REVIEW

**Comment by ChristianAchatz** [comment]
Thank you for your contribution! :)

I'll check the Travis 7.2 build and see what is going wrong. Back in a bit...

**Comment by ChristianAchatz** [comment]
Just found the issue and moved the session_cache_limiter() call to StreamMediaAction::run().

Question: when I now run my tests, a coverage report is generated at every single run. What I would like to see is an option to switch the coverage report on and off to get quick results w/o a report and use the report to double-check how I did in terms of coverage. Any idea?

Within my current workflow, I am using PHPStorm (which I highly recommend) and there is a noce integration of PHPUnit Code Coverage at the click of a button (seehttps://www.jetbrains.com/help/phpstorm/switching-between-code-coverage-suites.html). In case I want to check the coverage, I simply click the button to execute the tests with coverage and the IDE displays a nice tree with folders and files and their associated rates. Would that also be an option for you?

**Comment by martialblog** [comment]
@ChristianAchatz There's a --no-coverage flag in PHPUnit https://phpunit.readthedocs.io/en/8.0/textui.html#command-line-options

As for Editor integration, I'm not that familiar with PHPStorm (I'm an Emacs person). Personally I use the generated HTML report to check for untested code, then write some tests and repeat.

**Comment by ChristianAchatz** [comment]
--no-coverage works great!

You should definitely try PHPStorm. To my experience, it is the best IDE out there for a ton of reasons. :)

**Pull request merged**
